### ISSUE TITLE
Can't run any code on Windows

### ISSUE THREAD

**Issue by ismail** [albertlatacz/java-repl#1]
# java -version

java version "1.7.0_17"
Java(TM) SE Runtime Environment (build 1.7.0_17-b02)
Java HotSpot(TM) 64-Bit Server VM (build 23.7-b01, mixed mode)
# java -jar javarepl.jar

Welcome to JavaREPL version 61 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_17)
Type in expression to evaluate.
Type :help for more options.

> import java.io.*
> java.lang.NullPointerException
>         at javarepl.Evaluator.compile(Evaluator.java:204)
>         at javarepl.Evaluator.evaluateExpression(Evaluator.java:170)
>         at javarepl.Evaluator.evaluate(Evaluator.java:132)
>         at javarepl.Evaluator.evaluate(Evaluator.java:46)
>         at javarepl.commands.EvaluateExpression.evaluate(EvaluateExpression.java:26)
>         at javarepl.commands.EvaluateExpression.call(EvaluateExpression.java:21)
>         at javarepl.commands.EvaluateExpression.call(EvaluateExpression.java:15)
>         at javarepl.internal.totallylazy.$Functions$7.call(Functions.java:118)
>         at javarepl.internal.totallylazy.$Rule.call(Rule.java:24)
>         at javarepl.internal.totallylazy.$Rules.call(Rules.java:53)
>         at javarepl.internal.totallylazy.$Functions.call(Functions.java:76)
>         at javarepl.internal.totallylazy.$Function1.apply(Function1.java:13)
>         at javarepl.Main.run(Main.java:79)
>         at javarepl.Main.main(Main.java:25)

**Comment by sreejithbnaick** [comment]
Getting java.lang.NullPointerException for everything. I am using javarepl-428.jar downloaded from Github.

REPL Log:
Welcome to JavaREPL version 428 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_101)
Type expression to evaluate, :help for more options or press tab to auto-complete.
Connected to local instance at http://localhost:41321

JDK & Java Version:
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
