### ISSUE TITLE
Strange behaviour when piping commands

### ISSUE THREAD

**Issue by cmedianu** [albertlatacz/java-repl#101]
echo "1+1" | java -jar build/artifacts/javarepl-dev.build.jar
Welcome to JavaREPL version dev.build (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_91)
Type expression to evaluate, :help for more options or press tab to auto-complete.
java> 1+1
java.lang.Integer res0 = 2
java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java> java>
Terminating...

**Comment by albertlatacz** [comment]
piping is not supported
