### ISSUE TITLE
Having trouble building the application once I clone Git Repository.

### ISSUE THREAD

**Issue by XEROenvy** [albertlatacz/java-repl#103]
Hello I get the following output in the console when I right click the build.xml and "Run As" Ant Build:

Buildfile: C:\Users\Saad\git\java-repl\build.xml
build:
update:
clean:
     [java] Downloading http://jarjar.googlecode.com/files/jarjar-1.1.jar
     [java] Failed to download http://jarjar.googlecode.com/files/jarjar-1.1.jar (java.io.FileNotFoundException: http://jarjar.googlecode.com/files/jarjar-1.1.jar)

BUILD FAILED
C:\Users\Saad\git\java-repl\build.xml:192: The following error occurred while executing this line:
C:\Users\Saad\git\java-repl\build.xml:68: The following error occurred while executing this line:
C:\Users\Saad\git\java-repl\build\shavenmaven.xml:23: Java returned: 1

Total time: 612 milliseconds

Can anyone help point me in the right direction. I am using Windows 10 with a new install of Eclipse Neon. I know the instruction say to run "$ ant" but I'm not sure how to run that in Eclipse.

**Comment by XEROenvy** [comment]
I think I resolved this issue by removing the old location of the "jarjar-1.1.jar" location by looking at a post in the Pull Requests where lines were changed:

-http://jarjar.googlecode.com/files/jarjar-1.1.jar
 +https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/jarjar/jarjar-1.1.jar

That's great but now I am getting this issue where I think the manual.zip file under /lib is not able to be accessed. I downloaded the Archive utility for Eclipse but it still only opens in Explorer.exe on my machine and throws the error and the build fails...

Buildfile: C:\Users\Saad\git\java-repl\build.xml
build:
update:
clean:
compile:

BUILD FAILED
C:\Users\Saad\git\java-repl\build.xml:195: The following error occurred while executing this line:
C:\Users\Saad\git\java-repl\build.xml:98: Execute failed: java.io.IOException: Cannot run program "unzip": CreateProcess error=2, The system cannot find the file specified

Total time: 656 milliseconds

**Comment by attheveryend** [comment]
windows doesn't have the unzip.exe by default.  I grabbed one off the google and placed it somewhere already denoted in the system PATH variable, and off it went.  At least, until it refused to accept my additional packages I tried to import by default, because I have no real idea how to do what I want and suck at this, but I did get it to move past the unzip command.

**Comment by cmantas** [comment]
Thanks for the workaround @XEROenvy.
Here it is in a single command:
```echo 'diff --git a/build/build.dependencies b/build/build.dependencies
index dcbf914..dca8bec 100644
--- a/build/build.dependencies
+++ b/build/build.dependencies
@@ -2,7 +2,7 @@ mvn:org.hamcrest:hamcrest-core:jar:1.3
 mvn:org.hamcrest:hamcrest-library:jar:1.3
 mvn:junit:junit-dep:jar:4.8.2
 
-http://jarjar.googlecode.com/files/jarjar-1.1.jar
+https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/jarjar/jarjar-1.1.jar
 
 
 
' | git apply
```

**Comment by albertlatacz** [comment]
JarJar issue is now resolved.
