### ISSUE TITLE
Getting big amount of session terminations

### ISSUE THREAD

**Issue by jneureuther** [albertlatacz/java-repl#104]
Since the update (today?) I get a `Session terminated. Starting new session...` on nearly every command.

**Comment by albertlatacz** [comment]
There were quite a few deployments but should calm down now. Is it still happening for you?

**Comment by jneureuther** [comment]
Yes unfortunately it is still happening..

**Comment by jneureuther** [comment]
Ok, seems I have entered an invalid expression (`new Character((char)1);`). :angel:  
Everything is ok with valid ones. Sorry for disturbing and thanks for the great project (and hosting)!
