### ISSUE TITLE
Not able to download the jar 

### ISSUE THREAD

**Issue by saikrishna321** [albertlatacz/java-repl#105]
with the below version i'm unable to get the jar
        
<dependency>
            <groupId>com.javarepl</groupId>
            <artifactId>javarepl</artifactId>
            <version>1.0.1</version>
        </dependency>

           <repository>
                <id>albertlatacz.published</id>
                <url>http://albertlatacz.published.s3.amazonaws.com/repo</url>
            </repository>

**Comment by albertlatacz** [comment]
please use valid version e.g. 350

**Comment by albertlatacz** [comment]
Also, downloads are now available in releases section. 

[](https://github.com/albertlatacz/java-repl/releases)

**Comment by albertlatacz** [comment]
https://github.com/albertlatacz/java-repl/releases

**Comment by saikrishna321** [comment]
@albertlatacz 

```
<dependency>
            <groupId>javarepl</groupId>
            <artifactId>javarepl</artifactId>
            <version>371</version>
        </dependency>
```

not able to fetch 371
