### ISSUE TITLE
Question: How does auto complete work

### ISSUE THREAD

**Issue by saikrishna321** [albertlatacz/java-repl#108]
I have working on external core library appium java-client, we initialize the instance as follows

AppiumDriver driver = new AndroidDriver();

now for auto completion i need all the methods driver instance holds. 

@albertlatacz any help on this ?

**Comment by albertlatacz** [comment]
I'm coming to this project and reviewing things. Plan was to have autocomplete for instance methods but it seems not done. Will look into it in near future

**Comment by saikrishna321** [comment]
@albertlatacz it works 👍
