### ISSUE TITLE
Not able to build project 

### ISSUE THREAD

**Issue by saikrishna321** [albertlatacz/java-repl#109]
@albertlatacz getting the below error using the latest release 371

[ERROR] Failed to execute goal on project appiumrepljava: Could not resolve dependencies for project com.saikrishna.appium.repl:appiumrepljava:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: com.googlecode.totallylazy:totallylazy:jar:2.249, com.googlecode.utterlyidle:utterlyidle:jar:2.108, com.googlecode.yadic:yadic:jar:2.48: Failure to find com.googlecode.totallylazy:totallylazy:jar:2.249 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]

**Comment by albertlatacz** [comment]
Not sure why but I've switched to gradle now.

**Comment by albertlatacz** [comment]
Make sure you add maven repository [http://repo.bodar.com](http://repo.bodar.com)

**Comment by saikrishna321** [comment]
@albertlatacz that didnt help and i'm unable to find the latest from s3 repo 


[ERROR] Failed to execute goal on project appiumrepljava: Could not resolve dependencies for project com.saikrishna.appium.repl:appiumrepljava:jar:1.0-SNAPSHOT: Could not find artifact javarepl:javarepl:jar:414 in albertlatacz.published (http://albertlatacz.published.s3.amazonaws.com/repo)
