### ISSUE TITLE
It is not possible to set the port for JavaREPLClient Web.

### ISSUE THREAD

**Issue by guadaran** [albertlatacz/java-repl#128]
## Description

It is not possible to set the port for JavaREPLClient Web through the **--port** parameter. It always take a random port.

## Steps to reproduce
1) Execute:  `java -jar javarepl-428.jar --hostname=127.0.0.1 --port=8000`

## Result

```
Welcome to JavaREPL version 428 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121)
ERROR: Could not connect to remote REPL instance at http://127.0.0.1:8000
```

## Environment

**Java REPL Version:** [428](https://github.com/albertlatacz/java-repl/releases/tag/428)
**OS:** macOS Sierra 10.12.3
**Java:** 1.8.0_121

**Comment by fanglijun** [comment]
This should by documented
