### ISSUE TITLE
german umlaut ü (only the small one) is not correctly displayed

### ISSUE THREAD

**Issue by glockenstein** [albertlatacz/java-repl#64]
instead I see a ?

**Comment by albertlatacz** [comment]
That seems better now. 

<img width="1303" alt="screen shot 2016-11-28 at 18 42 24" src="https://cloud.githubusercontent.com/assets/2648270/20681206/80e4fc7e-b59a-11e6-9662-7ee39b197e93.png">
<img width="770" alt="screen shot 2016-11-28 at 18 41 22" src="https://cloud.githubusercontent.com/assets/2648270/20681205/80e447e8-b59a-11e6-843e-ce7262ad74a7.png">

**Comment by glockenstein** [comment]
But not in Windows:

java> "äöüÄÖÜß"
java.lang.String res0 = "õ÷³─Í▄▀"

**Comment by albertlatacz** [comment]
Aaa, yes, there was no work done to support windows.
