### ISSUE TITLE
Incorrect evaluation order for multiple expression in one line

### ISSUE THREAD

**Issue by mishadoff** [albertlatacz/java-repl#65]
Reproduce the problem:

```
java> int i = 10;
int i = 10
java> i = 20; System.out.println(i);
10
java.lang.Integer i = 20
```

I suppose it happens because of each line after pressing enter uses variables map from the snapshot before and not updated fro previous expression from that line.

**Comment by albertlatacz** [comment]
yes, that's correct. One per line at the moment but may look into that.
