### ISSUE TITLE
Consider supporting CTRL+D to close the REPL

### ISSUE THREAD

**Issue by ddossot** [albertlatacz/java-repl#67]
Many REPLs (Ruby, Haskell) can be terminated with `CTRL+d`. It would be nice if Java-REPL could be stopped the same way.

**Comment by rroblak** [comment]
+1

**Comment by Knorkebrot** [comment]
+1

`ctrl-d` issues an end-of-transmission character, and is therefor used as a shortcut to `exit`, `ctrl-c` on the other hand issues an end-of-text character and should terminate the current input, not the program itself :)

**Comment by soulrebel** [comment]
+1

**Comment by inodb** [comment]
:+1:

**Comment by suderio** [comment]
+1

**Comment by prem2014** [comment]
+ 1

**Comment by prem2014** [comment]
+1
