### ISSUE TITLE
Add the current project class path to the default class path

### ISSUE THREAD

**Issue by trustin** [albertlatacz/java-repl#7]
When I start a new JavaREPL pane in IntelliJ, all the auto-completion for the classes in the project works nicely, but it seems like JavaREPL fails to resolve those classes on evaluation.  For example:

```
java> import io.netty.util.*
ERROR: error: package io.netty.util does not exist

import io.netty.util.*;
^
```

**Comment by albertlatacz** [comment]
IntelliJ plugin is no longer supported
