### ISSUE TITLE
Automatically terminate JavaREPL process when its pane is closed via CTRL+F4

### ISSUE THREAD

**Issue by trustin** [albertlatacz/java-repl#8]
When I'm done with my JavaREPL session and I try to close the JavaREPL pane by pressing CTRL+F4, it always asks me if I want to terminate the JavaREPL process.  It would be nice if the process is terminated automatically when the pane is closed.

**Comment by albertlatacz** [comment]
Hi, IntelliJ plugin is no longer supported.
