### ISSUE TITLE
JavaREPL starts in cygwin but does not execute statements

### ISSUE THREAD

**Issue by mrt181** [albertlatacz/java-repl#92]
This is the output when i start it from cmd.exe. eerything work (e.g. tab auto-complete)

``` cmd
C:\cygwin64\home\user>java -jar javarepl.jar
Welcome to JavaREPL version 302 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_65)
Type expression to evaluate, :help for more options or press tab to auto-complete.
java> System.getPropert
getProperty(     getProperties(
java> System.getProperty("os.name")
java.lang.String res0 = "Windows 7"
java>
```

This is the output when I start from cygwin. Tab auto-complete does not work. The statement never finishes.

``` bash
user@machine ~
$ java -jar javarepl.jar
Welcome to JavaREPL version 302 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_65)
Type expression to evaluate, :help for more options or press tab to auto-complete.
java> System.getProperty("os.name")

```

**Comment by albertlatacz** [comment]
Hi, It was not designed/tested on Windows but I appreciate any help, as I don't really run Windows anywhere.

**Comment by RichardBradley** [comment]
This is a reasonable response. 
You might like to leave the issue open, to show that it's a known issue, to make this explanation visible to users and in case anyone turns up who has the time and expertise to fix it for us.
