### ISSUE TITLE
command to run java-repl in README.md doesn't work

### ISSUE THREAD

**Issue by ptepper** [albertlatacz/java-repl#98]
`java -jar javarepl.jar` will not run

`java -jar build/artifacts/javarepl-dev.build.jar` will :)

The readme should be updated so that it works by copy and pasting the command you give.

Otherwise, nice work, thanks for sharing!

**Comment by chuckwondo** [comment]
@ptepper The command works if you simply download a pre-built version, which is named `javarepl.jar` as given in the original command. However, I agree that the instructions should be updated to add the command that you provided, which is necessary only when building from source.

**Comment by ptepper** [comment]
@chuckwondo Hah, yea, I didn't both clicking the Download links, so I didn't realize they were links to download the pre-built jars. This being GitHub, I went on autopilot, cloned the repo and followed the build instructions. I guess the Download instructions could more clearly state that you're getting a pre-built version :)
